# Data

In [4]:
import numpy as np

In [7]:
import pandas as pd

In [8]:
df=pd.DataFrame({'text':['People Watch Campusx','CampusX watch CampusX','People Write Comment','Campusx Write Comment'],'output':[1,1,0,0,]})

In [9]:
df

text  output
0   People Watch Campusx       1
1  CampusX watch CampusX       1
2   People Write Comment       0
3  Campusx Write Comment       0

# 1.One Hot Encoding

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
OHE=OneHotEncoder()

In [14]:
encoder = OneHotEncoder(sparse=False)
transformed_data = encoder.fit_transform(df[['text']])

one_hot_encoded_df = pd.DataFrame(transformed_data, columns=encoder.get_feature_names_out(['text']))



C:\Users\acer\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [13]:
one_hot_encoded_df

text_CampusX watch CampusX  text_Campusx Write Comment  \
0                         0.0                         0.0   
1                         1.0                         0.0   
2                         0.0                         0.0   
3                         0.0                         1.0   

   text_People Watch Campusx  text_People Write Comment  
0                        1.0                        0.0  
1                        0.0                        0.0  
2                        0.0                        1.0  
3                        0.0                        0.0

## 2.Bag of Words

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
cv=CountVectorizer()
bow=cv.fit_transform(df['text'])

In [17]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [18]:
print(bow[0].toarray())

[[1 0 1 1 0]]


In [19]:
print(bow[1].toarray())

[[2 0 0 1 0]]


In [21]:
cv.transform(['Campusx watch and Write comment of Campusx']).toarray()

array([[2, 1, 0, 1, 1]], dtype=int64)

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
- Refer above link for more Parameters and better understanding of CountVectorizer

# 3.N-grams(Bi-grams, Tri-grams)

Bag of words is a special case of N-grams known as Unigrams

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))

### Bi-grams

In [23]:
bow=cv.fit_transform(df['text'])

In [24]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [25]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]


### Tri-grams

In [36]:
ab=CountVectorizer(ngram_range=(3,3))

In [37]:
bow=ab.fit_transform(df['text'])

In [38]:
print(ab.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}


In [39]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0]]
[[1 0 0 0]]


# 4.TF-IDF

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [41]:
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [46]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']


- We take log in IDF because it converts the large values into small values and smoothen the difference between high values and low values of Tf & IDF.

# Happy Learning....!